name: 'Bug report'
description: 'Create a report to help us improve the project'
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, steps to reproduce and screenshots
      placeholder: |
        - Device
        - Version
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the bug
    validations:
      required: true
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: By submitting this issue, you agree to follow our __Contributing Guidelines__ and __Code of Conduct__
      options:
        - label: I agree to follow this project's [__Code of Conduct__](https://github.com/GreenteaOS/.github/blob/kawaii/CODE_OF_CONDUCT.md)
          required: true
