// The Tofita Kernel
// Copyright (C) 2020 Oleh Petrenko
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, version 3 of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include <stdint.h>

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#ifndef NTDLL32_DLL
	#ifdef bit64
		#define NTDLL32_DLL __declspec(dllimport)
	#else
		#define NTDLL32_DLL __declspec(dllimport) __stdcall
	#endif
	extern const wchar_t* _wcmdln asm("_wcmdln");
#else
	__declspec(dllexport) const wchar_t* _wcmdln asm("_wcmdln") = L"_wcmdln TODO";
#endif
// TODO https://en.cppreference.com/w/cpp/numeric/bit_cast
extern "C" {
NTDLL32_DLL uint64_t KiFastSystemCall(uint64_t rcx, uint64_t rdx) asm("KiFastSystemCall");

#define STUB(name) NTDLL32_DLL uint32_t name(void* value) asm(#name);
#define LSTUB(name, link) NTDLL32_DLL uint32_t name(void* value) asm("*" #link);
LSTUB(LeaveCriticalSection, eaveCriticalSection)
LSTUB(LoadLibraryExW, oadLibraryExW)
LSTUB(LCMapStringW, CMapStringW)

LSTUB(LCMapStringA, CMapStringA)
LSTUB(LoadImageW, oadImageW)
LSTUB(LoadLibraryA, oadLibraryA)
LSTUB(LoadLibraryW, oadLibraryW)
LSTUB(LoadMenuW, oadMenuW)
LSTUB(LoadStringW, oadStringW)
LSTUB(LocalFree, ocalFree)
LSTUB(LocalReAlloc, ocalReAlloc)
LSTUB(LockFile, ockFile)
LSTUB(lstrcatW, strcatW)
LSTUB(lstrcpynA, strcpynA)
LSTUB(lstrcpyW, strcpyW)
LSTUB(lstrlenW, strlenW)

STUB(MapVirtualKeyExW)
STUB(GetCurrentProcess)
STUB(WriteConsoleW)
STUB(CloseHandle)
STUB(CreateFileW)
STUB(ReadConsoleW)
STUB(ReadFile)
STUB(SetFilePointerEx)
STUB(GetFileSizeEx)
STUB(GetConsoleMode)
STUB(GetConsoleOutputCP)
STUB(FlushFileBuffers)
STUB(HeapReAlloc)
STUB(QueryPerformanceCounter)
STUB(GetCurrentProcessId)
STUB(GetCurrentThreadId)
STUB(GetSystemTimeAsFileTime)
STUB(InitializeSListHead)
STUB(RtlCaptureContext)
STUB(RtlLookupFunctionEntry)
STUB(RtlVirtualUnwind)
STUB(IsDebuggerPresent)
STUB(UnhandledExceptionFilter)
STUB(SetUnhandledExceptionFilter)
STUB(GetStartupInfoW)
STUB(IsProcessorFeaturePresent)
STUB(GetModuleHandleW)
STUB(RtlUnwindEx)
STUB(InterlockedPushEntrySList)
STUB(InterlockedFlushSList)
STUB(GetLastError)
STUB(SetLastError)
STUB(EnterCriticalSection)
STUB(DeleteCriticalSection)
STUB(InitializeCriticalSectionAndSpinCount)
STUB(TlsAlloc)
STUB(TlsGetValue)
STUB(TlsSetValue)
STUB(TlsFree)
STUB(FreeLibrary)
STUB(GetProcAddress)
STUB(EncodePointer)
STUB(RaiseException)
STUB(RtlPcToFileHeader)
STUB(GetStdHandle)
STUB(WriteFile)
STUB(GetModuleFileNameW)
STUB(RtlUnwind)
STUB(TerminateProcess)
STUB(GetModuleHandleExW)
STUB(GetCurrentThread)
STUB(OutputDebugStringW)
STUB(HeapFree)
STUB(FindClose)
STUB(FindFirstFileExW)
STUB(FindNextFileW)
STUB(IsValidCodePage)
STUB(GetACP)
STUB(GetOEMCP)
STUB(GetCPInfo)
STUB(GetCommandLineA)
STUB(GetCommandLineW)
STUB(MultiByteToWideChar)
STUB(WideCharToMultiByte)
STUB(GetEnvironmentStringsW)
STUB(FreeEnvironmentStringsW)
STUB(SetEnvironmentVariableW)
STUB(SetStdHandle)
STUB(GetFileType)
STUB(GetStringTypeW)
STUB(GetLocaleInfoW)
STUB(IsValidLocale)
STUB(GetUserDefaultLCID)
STUB(EnumSystemLocalesW)
STUB(GetDateFormatW)
STUB(GetTimeFormatW)
STUB(CompareStringW)
STUB(GetProcessHeap)
STUB(SetConsoleCtrlHandler)
STUB(HeapSize)

STUB(AppendMenuW)
STUB(Beep)
STUB(CallWindowProcW)
STUB(CheckDlgButton)
STUB(CheckMenuItem)
STUB(CheckRadioButton)
STUB(CloseClipboard)
STUB(CreateDirectoryA)
STUB(CreateDirectoryW)
STUB(CreatePipe)
STUB(CreatePopupMenu)
STUB(CreateProcessA)
STUB(CreateProcessW)
STUB(CreateThread)
STUB(DbgPrint)
STUB(DeleteFileA)
STUB(DeleteFileW)
STUB(DestroyIcon)
STUB(DestroyMenu)
STUB(DrawFrameControl)
STUB(DrawStateW)
STUB(DuplicateHandle)
STUB(EmptyClipboard)
STUB(EnableMenuItem)
STUB(EnableWindow)
STUB(EnumChildWindows)
STUB(EnumResourceLanguagesA)
STUB(ExitThread)
STUB(FindFirstFileA)
STUB(FindFirstFileW)
STUB(FindNextFileA)
STUB(FreeEnvironmentStringsA)
STUB(GetAsyncKeyState)
STUB(GetClassNameW)
STUB(GetClipboardData)
STUB(GetCurrentDirectoryA)
STUB(GetCurrentDirectoryW)
STUB(GetDateFormatA)
STUB(GetDiskFreeSpaceA)
STUB(GetDlgItem)
STUB(GetDlgItemTextW)
STUB(GetDriveTypeA)
STUB(GetDriveTypeW)
STUB(GetEnvironmentStrings)
STUB(GetEnvironmentVariableA)
STUB(GetExitCodeProcess)
STUB(GetFileAttributesA)
STUB(GetFileAttributesExA)
STUB(GetFileAttributesExW)
STUB(GetFileAttributesW)
STUB(GetFileInformationByHandle)
STUB(GetFocus)
STUB(GetFullPathNameA)
STUB(GetFullPathNameW)
STUB(GetKeyboardLayout)
STUB(GetKeyboardState)
STUB(GetLocaleInfoA)
STUB(GetLocalTime)
STUB(GetMenu)
STUB(GetModuleFileNameA)
STUB(GetModuleHandleA)
STUB(GetNumberOfConsoleInputEvents)
STUB(GetParent)
STUB(GetProfileIntW)
STUB(GetStartupInfoA)
STUB(GetStockObject)
STUB(GetStringTypeA)
STUB(GetStringTypeExA)
STUB(GetSubMenu)
STUB(GetSystemDefaultLCID)
STUB(GetSystemMetrics)
STUB(GetTempFileNameA)
STUB(GetTempFileNameW)
STUB(GetTextExtentPoint32W)
STUB(GetTickCount)
STUB(GetTimeFormatA)
STUB(GetTimeZoneInformation)
STUB(GetVersionExW)
STUB(GetWindowLongPtrW)
STUB(GetWindowRect)
STUB(GetWindowTextW)
STUB(GlobalLock)
STUB(GlobalUnlock)
STUB(HeapCompact)
STUB(HeapValidate)
STUB(HeapWalk)
STUB(InitCommonControls)
STUB(InitializeCriticalSection)
STUB(InvalidateRect)
STUB(IsClipboardFormatAvailable)
STUB(IsDlgButtonChecked)
STUB(IsWindow)
STUB(IsWindowEnabled)
STUB(MoveFileExA)
STUB(MoveFileExW)
STUB(MoveWindow)
STUB(OpenClipboard)
STUB(PeekConsoleInputA)
STUB(PostMessageW)
STUB(ReadConsoleA)
STUB(RegCloseKey)
STUB(RegCreateKeyExW)
STUB(RegOpenKeyExW)
STUB(RegQueryValueExW)
STUB(RegSetValueExW)
STUB(RemoveDirectoryA)
STUB(RemoveDirectoryW)
STUB(ResumeThread)
STUB(RtlAllocateHeap)
STUB(RtlAreBitsClear)
STUB(RtlAreBitsSet)
STUB(RtlFreeHeap)
STUB(RtlInitializeBitMap)
STUB(RtlRaiseException)
STUB(RtlSecondsSince1970ToTime)
STUB(RtlSetBits)
STUB(RtlTimeToSecondsSince1970)
STUB(SearchPathA)
STUB(SearchPathW)
STUB(SendDlgItemMessageW)
STUB(SendMessageW)
STUB(SetBkMode)
STUB(SetClipboardData)
STUB(SetConsoleMode)
STUB(SetCurrentDirectoryA)
STUB(SetCurrentDirectoryW)
STUB(SetDlgItemTextW)
STUB(SetEndOfFile)
STUB(SetErrorMode)
STUB(SetFileAttributesA)
STUB(SetFileAttributesW)
STUB(SetFilePointer)
STUB(SetFileTime)
STUB(SetFocus)
STUB(SetLocalTime)
STUB(SetMenu)
STUB(SetTextColor)
STUB(SetWindowLongPtrW)
STUB(ShellAboutW)
STUB(Sleep)
STUB(ToAsciiEx)
STUB(TrackMouseEvent)
STUB(TrackPopupMenu)
STUB(TryEnterCriticalSection)
STUB(UnlockFile)
STUB(vDbgPrintExWithPrefix)
STUB(VirtualProtect)
STUB(WaitForSingleObject)
STUB(WriteConsoleA)
STUB(WriteProfileStringW)

STUB(wcschr)
STUB(__lconv_init)
STUB(signal)
STUB(_iob)
STUB(fprintf)
STUB(_commode)
STUB(_fmode)
STUB(__winitenv)
STUB(_initterm)
STUB(_fpreset)
STUB(_cexit)
STUB(exit)
STUB(__set_app_type)
STUB(__wgetmainargs)
STUB(_amsg_exit)
STUB(__setusermatherr)
STUB(_wcsicmp)
STUB(wcslen)
STUB(wcscpy)
STUB(wcscat)
STUB(_strupr)
STUB(_strdup)
STUB(strlen)
STUB(memset)
STUB(memcpy)
STUB(swscanf)
STUB(swprintf)
STUB(cosh)
STUB(memmove)
STUB(wcscmp)
STUB(acos)
STUB(asin)
STUB(atan)
STUB(cos)
STUB(exp)
STUB(fabs)
STUB(fmod)
STUB(log)
STUB(log10)
STUB(pow)
STUB(sin)
STUB(sinh)
STUB(sqrt)
STUB(tan)
STUB(tanh)
STUB(ceil)
STUB(modf)
STUB(_finite)
STUB(_isnan)
STUB(free)
}
