name: Building image

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-all:
    name: 'Building'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2022 ]
        node-version: [ 16.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Hexa
      run: |
        git clone --depth 1 https://github.com/hexalang/Hexa.git

    - name: Prepare Hexa
      run: |
        node --trace-uncaught ./Hexa/bootstrap.js ./Hexa/hexa.json

    - name: Get Teapot
      run: |
        git clone --depth 1 https://github.com/GreenteaOS/Teapot.git ../Teapot

    - name: Building Tofita
      run: |
        node --trace-uncaught ./Hexa/hexa-node.js build/hexa.json
        node --trace-uncaught build.js init asm uefi dll build iso

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: greentea-uefi64-image
        path: C:\Tea\greenteaos-uefi64.iso
